<?php
/**
 * Created by PhpStorm.
 * User: evelyn
 * Date: 2015/10/26
 * Time: 下午 12:14
 */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <link href='https://fonts.googleapis.com/css?family=Chivo:900' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/github-dark.css" media="screen">
    <link rel="stylesheet" type="text/css" href="stylesheets/print.css" media="print">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>Evelyn's Collections</title>
</head>

<body>
<div id="container">
    <div class="inner">

        <header>
            <h1>Evelyn's Collections</h1>
            <h2></h2>
        </header>

<!--        <section id="downloads" class="clearfix">-->
<!--            <a href="https://github.com/evelynocean" id="view-on-github" class="button"><span>View on GitHub</span></a>-->
<!--        </section>-->

        <hr>

        <section id="main_content">

            <h3>
                <a id="welcome-to-github-pages" class="anchor" href="#framework_practice" aria-hidden="true"><span class="octicon octicon-link"></span>framework_practice</a>
                <a href="https://github.com/evelynocean/framework_practice"><U>Link</U></a>
            </h3>
            <p>目的：練習實作一個frame work, 以了解frame work 機制<br>
                內容：<br>
                使用工具：<br>
            </p>

            <h3>
                <a id="welcome-to-github-pages" class="anchor" href="#poker_sevens" aria-hidden="true"><span class="octicon octicon-link"></span>poker_sevens</a>
                <a href="https://github.com/evelynocean/poker_sevens"><U>Link</U></a>
            </h3>
            <p>目的：<br>
                內容：<br>
                使用工具：<br>
            </p>

            <h3>
                <a id="welcome-to-github-pages" class="anchor" href="#" aria-hidden="true"><span class="octicon octicon-link"></span></a>
                <a href="https://github.com/evelynocean/"><U>Link</U></a>
            </h3>
            <p>目的：<br>
                內容：<br>
                使用工具：<br>
            </p>


       </section>

        <footer>
            This page was generated by <a href="https://pages.github.com">GitHub Pages</a>. Tactile theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.
        </footer>


    </div>
</div>
</body>
</html>